name: Run Topic Analytics

on:
  schedule:
    - cron: '0 5 * * 1-5'  # Tous les jours de la semaine (lundi à vendredi) à 9h UTC
  workflow_dispatch:     # Permet aussi de le lancer manuellement depuis GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          BLOB_CONNECTION_STRING: ${{ secrets.BLOB_CONNECTION_STRING }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          VERSION_ID: ${{ secrets.VERSION_ID }}
        run: python function_app.py
